function descriptors = getTrackletHeadTailDescriptorIdx(tracklets, folderOUT)
	% GETTRACKLETHEADTAILDESCRIPTORIDX returns the indices descriptors of the tracklets head and tail together with the frame numbers
	% Inputs:
	% 	tracklets = a matrix of tracklets as generated by generateTracklets()
	% 	folderOUT = folder containing im*.mat files which contain a feature vector and location of each cell. One file per image.
	% Outputs:
	% 	descriptors = a numTracklets x 4 matrix containing:
	%		frameA, descriptorIdxA, frameB, descriptorIdxB

	% Usage:
	% descriptorIdx = getTrackletHeadTailDescriptorIdx(tracklets, params.outFolder);

	numTracklets = size(tracklets, 1);

	% TODO: bring this in from a config file
	imPrefix = 'im';

	% Get the number of features of each descriptor
	dataFiles = dir(fullfile(folderOUT, sprintf('%s*.mat', imPrefix)));
	data1 = load(fullfile(folderOUT, dataFiles(1).name));

	numFeatures = length(data1.descriptors) + 2; % together with dots
	descriptors = zeros(numTracklets, numFeatures, 2, 'single');
	
	for i=1:numTracklets
		trackletFrames = find(tracklets(i, :));

		indices = [trackletFrames(1) trackletFrames(end)];

		for headtail=1:numel(unique(indices))
			data = load(fullfile(folderOUT, dataFiles(indices(headtail)).name));
			deses = combineDescriptorsWithDots(data.descriptors, data.dots);

			des = deses(tracklets(i, indices(headtail)), :);

			descriptors(i, :, headtail) = des;
			if length(trackletFrames) == 1
				descriptors(i, :, headtail + 1) = des;
			end
		end
	end

	% For each tracklet extract each frame number of head and tail
	% Get the Frame number of the head
	% get the cell index of the head
	% Load the descriptor of head
	% Get the Frame number of the tail
	% get the cell index of the tail
	% Load the descriptor of the tail
end