function Liks = computeLikelihoods(tracklets, hypothesis, hypTypes, options)
	% COMPUTELIKELIHOODS Computes the likelihood of each hypothesis
	% Inputs:
	% 	tracklets = the tracklets matrix generated by generateTracklets()
	% 	hypothesis = the hypothesis matrix generate by generateHypothesisMatrix()
	%	hypTypes = a vector indicating the type of hypothesis, as generateb by generateHypothesisMatrix()
	% 	options = a struct with options
	% Outputs:
	% 	Liks = a column vector of length numHypothesis containing likelihoods for each hypothesis

	% TODO: remove this:
	% To compute the probablities I will need:
	% 	- to compute Pfp and Ptp I will need:
	% 		- MISS DETECTION rate of cell_detector
	% 		- number of cells in tracklet
	% 	- to compute the Plink I will need:
	% 		A FEATURE VECTOR of first and last tracklet in sequence (CELL DESCRIPTOR)
	% 		including motion feature and distance to following tracklet
	% 		check that the spatial distribution of cells in tracklets is similar
	% 	- to compute init prob I will need
	% 		temporal and spatial distribution of tracks before it,
	% 		and its proximity to a boundary  (IMAGE SIZE)
	% 	- to compute term prob I will need
	% 		temporal and spatial distribution of tracks after it,
	% 		and its proximity to a boundary

	%------------------------------------------------------------------Options
	if nargin < 2; options = struct; end

	% This should mirror the types in generateHypothesisMatrix()
	TYPE_INIT = 1;
	TYPE_TERM = 2;
	TYPE_FP = 3;
	TYPE_LINK = 4;

	MISS_DETECTION_RATE = 0.3;  % TODO: load real value from an external param
	% file

	%--------------------------------------------------------Preallocate space
	numHypothesis = size(hypothesis, 1);
	numTracklets = size(tracklets, 1);

	% Likelihood vector
	Liks = zeros(numHypothesis, 1);

	%-------------------------------------------------Precompute probabilities

	linkHypothesisIdx = find(hypTypes == TYPE_LINK);
	linkHypothesis = hypothesis(linkHypothesisIdx, :);
	pLinks = computePlink(linkHypothesis);
	[pFPs, pTPs] = computeTruthnessProbs(1:numTracklets);

	%------------------------------------------------------Compute likelihoods

	% Although generateHypothesisMatrix orders the hypothesis is an easy to remember order, I do not rely on the order, but on the types given in hypTypes

	% Compute initialization hypothesis
	Liks(hypTypes == TYPE_INIT) = 0.1;

	% Compute termination hypothesis
	Liks(hypTypes == TYPE_TERM) = 0.2;

	% Compute false positive hypothesis
	[I, ~] = find(hypothesis(hypTypes == TYPE_FP, 1:numTracklets));
	Liks(hypTypes == TYPE_FP) = pFPs(I);

	% Compute link hypothesis
	for i=1:numel(linkHypothesisIdx)
		[~, J] = find(linkHypothesis(i, :));
		Liks(linkHypothesisIdx(i)) = pLinks(J(1), J(2)-numTracklets);
	end

	function P = computePlink(linkHypothesis)
		% COMPUTEPLINK for each link hypothesis compute the probability of linking
		% Inputs:
		% 	linkHypothesis= a (sparse) matrix of dimensions numTracklets x numTracklets containing 1 if the tracks could potentially be linked
		% Outputs:
		% 	P = the probability of linking the pairs of tracklets as evaluated by a learned model, in the form a of matrix the same size as linkHypothesis;

		% Algorithm outline:
		% Find init and end of each tracklet
		% find the corresponding index of the cell in the image
		% find the corresponding cell descriptor
		% TODO: augement the cell descriptor with motion features
		% create a sparse matrix like linkHypothesis
		% for each possible link hypothesis evaluate the model

		% For each tracklet, find where it starts and where it ends

		datafolder = fullfile('..', 'data', 'series30greenOUT');
		numLinkHypothesis = size(linkHypothesis, 1);

		P = sparse([],[],[], numTracklets, numTracklets);

		trackletPairs = zeros(numLinkHypothesis, 2);
		for i=1:numLinkHypothesis
			[~, J] = find(linkHypothesis(i, :));
			trackletPairs(i, :) = [J(1) J(2)-numTracklets];
		end

		numFeatures = 102; % together with dots
		descriptorDistMatrix = zeros(size(trackletPairs, 1), numFeatures);
		uniqueTracklets = unique(trackletPairs(:));
		descriptors = zeros(numel(uniqueTracklets), numFeatures, 2);

		% for each unique tracklet load the descriptor of the head and tail
		% TODO I only need to load one of head/tail for each tracklet
		for i=1:numel(uniqueTracklets)
			[~, J] = find(max(tracklets(uniqueTracklets(i), :, :), [], 3));
			trackletStartFrame = J(1);
			trackletEndFrame = J(end);

			dataA = load(fullfile(datafolder, sprintf('im%03d.mat', trackletStartFrame)));
			dataB = load(fullfile(datafolder, sprintf('im%03d.mat', trackletEndFrame)));

			posStartFrame = tracklets(uniqueTracklets(i), trackletStartFrame, :);
			posStartFrame = [posStartFrame(1,1,1) posStartFrame(1,1,2)];
			idx=ismember(dataA.dots, posStartFrame,'rows');
			desA = dataA.descriptors(idx, :);
			dotsA = dataA.dots(idx, :);

			posEndFrame = tracklets(uniqueTracklets(i), trackletEndFrame, :);
			posEndFrame = [posEndFrame(1,1,1) posEndFrame(1,1,2)];
			idx=ismember(dataB.dots, posEndFrame,'rows');
			desB = dataB.descriptors(idx, :);
			dotsB = dataB.dots(idx, :);

			desA = combineDescriptorsWithDots(desA, dotsA);
			desB = combineDescriptorsWithDots(desB, dotsB);

			descriptors(uniqueTracklets(i), :, 1) = desA;
			descriptors(uniqueTracklets(i), :, 2) = desB;
		end

		Ds = zeros(numLinkHypothesis, numFeatures);
		for i=1:numLinkHypothesis
			trackletA = trackletPairs(i, 1);
			trackletB = trackletPairs(i, 2);

			D = euclideanDistance(descriptors(trackletA, :, 2), ... % tail
								  descriptors(trackletB, :, 1)); % head
			Ds(i, :) = D;
		end

		matchP = testMatcherTrackletJoinerNB(Ds);
		for i=1:numLinkHypothesis
			P(trackletPairs(i, 1), trackletPairs(i, 2)) = matchP(i);
		end		
	end

	function [FP, TP] = computeTruthnessProbs(trackletIdx)
		% COMPUTETRUTHNESSPROBS Computes the probability that a tracklet is a false positive or a true positive
		% Inputs:
		% 	trackletIdx = indices of tracklets
		% Outputs:
		% 	FP = corresponding false positive probability
		% 	TP = corresponding true positive probability
		
		len = sum(max(tracklets(trackletIdx, :, :), [], 3) ~= 0, 2);
		FP = MISS_DETECTION_RATE .^ len;
		TP = 1 - FP;
	end
end