function descriptors = getTrackletDescriptors(tracklets, folderOUT)
	% GETTRACKLETDESCRIPTORS computes the descriptors of the tracklets head and tail
	% Inputs:
	% 	tracklets = a matrix of tracklets as generated by generateTracklets()
	% 	folderOUT = folder containing im*.mat files which contain a feature vector and location of each cell. One file per image.
	% Outputs:
	% 	descriptors = a numTracklets x numFeatures x 2 matrix containing descriptors of the head and tail of each tracklet

	

end