function descriptors = getTrackletHeadTailDescriptors(tracklets, folderOUT)
	% GETTRACKLETHEADTAILDESCRIPTORS returns the descriptors of the tracklets head and tail
	% Inputs:
	% 	tracklets = a matrix of tracklets as generated by generateTracklets()
	% 	folderOUT = folder containing im*.mat files which contain a feature vector and location of each cell. One file per image.
	% Outputs:
	% 	descriptors = a numTracklets x numFeatures x 2 matrix containing descriptors of the head and tail of each tracklet

	numTracklets = size(tracklets, 1);
	imPrefix = 'im';
	imNamesDigits = '3';
	% Get the number of features of each descriptor
	dataFiles = dir(fullfile(folderOUT, sprintf('%s*.mat', imPrefix)));
	data1 = load(fullfile(folderOUT, dataFiles(1).name));

	numFeatures = length(data1.descriptors) + 2; % together with dots
	descriptors = zeros(numTracklets, numFeatures, 2);
	
	for i=1:numTracklets
		trackletFrames = find(max(tracklets(i, :, :), [], 3));

		indices = [trackletFrames(1) trackletFrames(end)];

		for headtail=1:numel(unique(indices))
			data = load(fullfile(folderOUT, dataFiles(indices(headtail)).name));
			deses = combineDescriptorsWithDots(data.descriptors, data.dots);

			% find the correct descriptor corresponding to the tracklet position
			loc = [tracklets(i, indices(headtail), 1) tracklets(i, indices(headtail), 2)];

			idx = ismember(data.dots, loc, 'rows');
			des = deses(idx, :);

			descriptors(i, :, headtail) = des;
			if length(trackletFrames) == 1
				descriptors(i, :, headtail + 1) = des;
			end
		end
	end

	% For each tracklet extract each frame number of head and tail
	% Get the Frame number of the head
	% get the cell index of the head
	% Load the descriptor of head
	% Get the Frame number of the tail
	% get the cell index of the tail
	% Load the descriptor of the tail
end